# Generated by Django 5.0.7 on 2024-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewsapp', '0002_category_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='news_categories',
            field=models.ManyToManyField(to='mynewsapp.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
